spring:
  profiles:
    active: dev
  autoconfigure:
      exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration , org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

logging: 
  file: D:\RnD\stream-listener-platform\communication-platform\logs.log
  level:
    root: INFO
    com: 
      amazonaws: INFO
    org:
      apache: 
        http: INFO
